# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzJmMGJiZTAzNTgwNDM3MDUxZTI1ODY1OTRmMjJhMjI1ZjczN2IxNGQ4NDFkM2QxYTVhNzIzMzc2ODRkYjU3NzA1MDJiMjkxOTMyOWM0NmE2MGY1MTJkYTJmNmVmYmEzZTk2NTVjM2QxZGI3OWUyNDA3ZTYzMDRkYWQ4MDQ4YTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
